Update to RSpec 3.4.0, fixing failures and deprecation warnings
All deprecation warnings were found using the following snippet.

    RSpec.configure do |config|
      config.raise_errors_for_deprecations!
    end

Trimmed list of failures:

    1) DebugController GET /debug displays the current Ruby version
       Failure/Error: expect(page).to have_tag("dd", text: /#{RUBY_VERSION}/)

         --------------------------------------------------------------------------------
         RSpec::Matchers::NokogiriMatcher implements a legacy RSpec matcher
         protocol. For the current protocol you should expose the failure messages
         via the `failure_message` and `failure_message_when_negated` methods.
         --------------------------------------------------------------------------------

    14) FirstRunController when a user has not been setup GET /setup/tutorial
          displays the tutorial and completes setup
        Failure/Error: UserRepository.stub(fetch: user)
          Using `stub` from rspec-mocks' old `:should` syntax without explicitly
            enabling the syntax is deprecated. Use the new `:expect` syntax or
            explicitly enable `:should` instead.

    26) FeverAPI::ReadFeedsGroups returns a list of groups requested through feeds
        Failure/Error: feed_repository.stub_chain(:in_group, :order).and_return(feeds)
          Using `stub_chain` from rspec-mocks' old `:should` syntax without
            explicitly enabling the syntax is deprecated. Use the new `:expect`
            syntax or explicitly enable `:should` instead.

    30) Feed importing Valid feed Importing for the second time new entries creates new stories
        Failure/Error: expect { fetch_feed(feed) }.to change { feed.stories.count }.by(1).to(6)

        NoMethodError:
          undefined method `to' for #<RSpec::Matchers::BuiltIn::ChangeRelatively:0x007f0629f8a0d0>

    29 deprecations found.

    Finished in 3.08 seconds (files took 1.51 seconds to load)
    193 examples, 30 failures